# .github/workflows/terraform_apply_template.yml

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.matrix) }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume:        ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region:            ${{ matrix.region }}
          role-duration-seconds: 3600

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: terraform init
        run: terraform -chdir=${{ matrix.folder }} init -reconfigure

      - name: terraform validate
        run: terraform -chdir=${{ matrix.folder }} validate

      - name: terraform plan
        id: plan
        run: |
          terraform -chdir=${{ matrix.folder }} plan \
            -out=tfplan.binary \
            -no-color 2>&1 | tee plan_output.txt

          PLAN=$(cat plan_output.txt)
          echo "output<<EOF"  >> $GITHUB_OUTPUT
          echo "$PLAN"        >> $GITHUB_OUTPUT
          echo "EOF"          >> $GITHUB_OUTPUT
        env:
          TF_VAR_role_arn:    ${{ secrets.AWS_IAM_ROLE_ARN }}
          TF_VAR_environment: ${{ inputs.environment }}
          TF_VAR_aws_region:  ${{ matrix.region }}

      - name: terraform apply
        id: apply
        run: |
          terraform -chdir=${{ matrix.folder }} apply \
            -no-color \
            tfplan.binary 2>&1 | tee apply_output.txt

          APPLY=$(cat apply_output.txt)
          echo "output<<EOF"  >> $GITHUB_OUTPUT
          echo "$APPLY"       >> $GITHUB_OUTPUT
          echo "EOF"          >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: check apply status
        if: steps.apply.outcome == 'failure'
        run: exit 1